name: test_example
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.5 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.2
  isar_generator: ^3.0.5
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  bloc: ^8.1.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  grpc: ^3.1.0
  isar: ^3.0.5
  fullstack_base:
    path: ../fullstack_base
