name: protoc_fullstack
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dart_style: ^2.2.4
  fixnum: ^1.0.1
  protobuf: ^3.1.0
  shell: ^2.0.0
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  lints: ^3.0.0
  test: ^1.24.9
