name: fullstack_base
description: A sample command-line application.
version: 1.0.0+1
# homepage: https://www.example.com

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  grpc: ^3.0.2
  protobuf: ^3.1.0
  fixnum: ^1.0.1
  isar: ^3.0.0
  bloc: ^8.1.0
  equatable: ^2.0.5
  logger: ^2.0.2+1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.16.0
