name: fullstack_base
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0-271.7.beta <3.0.0'

dependencies:
  grpc: ^3.0.2
  protobuf: ^2.1.0
  logger: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
